language: ruby
cache: bundler

rvm:
  - 2.5.3

before_install:
  - gem update --system
  - gem install bundler
  - git clone https://github.com/slatedocs/slate.git slate

script:
  - rm -r slate/source
  - cp source slate/source
  - cd slate
  - exec middleman build

deploy:
  provider: pages
  local_dir: slate/build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master