language: ruby

rvm:
  - 2.5.3

cache:
  directories:
    - /home/travis/.rvm/
    - slate/vendor/bundle

before_install:
  - mv slate temp
  - git clone https://github.com/ChatKitty/slate.git slate
  - rm -r slate/source
  - cp -r source slate/source
  - mv -v temp/* slate/
  - cd slate
  - gem update --system
  - gem install bundler

script:
  - ./deploy.sh --source-only

deploy:
  provider: pages
  local_dir: slate/build/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master